apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  namespace: sb-jaeger-tracing-demo
  labels:
    app: producer
spec:
  selector:
    app: producer
  type: ClusterIP
  ports:
  - port: 5672
    name: rabbitmq
  - port: 8081
    name: serverport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-sample
  namespace: sb-jaeger-tracing-demo
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: ${REGISTRY_ADDR}/rabbitmq-producer:9
        name: producer-sample
        env:
        - name: JAEGER_UDP_SENDER_HOST
          value: jaeger-agent.istio-system.svc.cluster.local 
        - name: RABBITMQ_HOST
          value: rabbitmq-svc.sb-jaeger-tracing-demo.svc.cluster.local
